"""empty message

Revision ID: 301bcef76f39
Revises: 3175c4beabf8
Create Date: 2020-05-03 00:19:01.378096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301bcef76f39'
down_revision = '3175c4beabf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('end_index', sa.Integer(), nullable=True))
    op.add_column('snippet', sa.Column('start_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snippet', 'start_index')
    op.drop_column('snippet', 'end_index')
    # ### end Alembic commands ###
