"""empty message

Revision ID: 3175c4beabf8
Revises: 
Create Date: 2020-05-02 14:37:16.728860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3175c4beabf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=150), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('content', sa.String(length=10000), nullable=True),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('answer', sa.String(length=50), nullable=True),
    sa.Column('alternatives', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snippet')
    op.drop_table('section')
    op.drop_table('article')
    # ### end Alembic commands ###
