"""empty message

Revision ID: 83d53e71ae9a
Revises: 301bcef76f39
Create Date: 2020-05-08 17:10:49.103033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d53e71ae9a'
down_revision = '301bcef76f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'title')
    # ### end Alembic commands ###
